"""Only generated bytes, temporary databases and mocked tools; no business media."""

from __future__ import annotations

import hashlib
import importlib
import json
import os
import shutil
import sys
import uuid
from datetime import UTC, datetime
from io import BytesIO
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest
from fastapi import FastAPI, UploadFile
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.config.settings import Settings
from app.services import video_preparation as preparation


@pytest.fixture(autouse=True)
def current_application_modules() -> None:
    """Other isolated API tests replace app modules; patch the current instances."""
    global preparation, Settings
    preparation = importlib.import_module("app.services.video_preparation")
    Settings = importlib.import_module("app.config.settings").Settings


def _settings(tmp_path: Path, **kwargs: Any) -> Settings:
    values = {
        "data_dir": tmp_path / "data",
        "video_preparation_enabled": True,
        "video_preparation_min_free_bytes": 0,
        "video_preparation_max_output_bytes": 1024,
        "person_detector": "whole_frame",
        "face_recognition_on_ingest": False,
        "vector_index_on_ingest": False,
        "vector_index_on_ingest_background": False,
        "reid_enabled": False,
        "milvus_enabled": False,
        "vlm_provider": "none",
        "vlm_structured_background": False,
        "vlm_structured_on_ingest": False,
        "appearance_tone_on_ingest": False,
    }
    values.update(kwargs)
    return Settings(_env_file=None, **values)


def _source(settings: Settings, *, suffix: str = ".avi", payload: bytes | None = None) -> Path:
    settings.videos_dir.mkdir(parents=True, exist_ok=True)
    path = settings.videos_dir / f"{uuid.uuid4()}{suffix}"
    path.write_bytes(
        payload if payload is not None else b"RIFF" + b"\x00" * 4 + b"AVI " + b"X" * 64
    )
    return path


def _metadata(*, codec: str = "mjpeg", **kwargs: Any) -> bytes:
    stream = {
        "codec_name": codec,
        "pix_fmt": "yuv420p",
        "width": 64,
        "height": 48,
        "duration": "0.5",
    }
    stream.update(kwargs)
    return json.dumps({"streams": [stream], "format": {"duration": "0.5"}}).encode()


@pytest.fixture
def fake_tools(monkeypatch: pytest.MonkeyPatch) -> list[list[str]]:
    commands: list[list[str]] = []

    def run(arguments: list[str], **_kwargs: Any) -> bytes:
        commands.append(arguments)
        if "-select_streams" in arguments:
            selector = arguments[arguments.index("-select_streams") + 1]
            if selector == "a:0":
                return b'{"streams":[]}'
            codec = "h264" if arguments[-1].endswith((".partial", ".mp4")) else "mjpeg"
            return _metadata(codec=codec)
        Path(arguments[-1]).write_bytes(b"\x00\x00\x00\x18ftyp" + b"synthetic playback" * 10)
        return b""

    monkeypatch.setattr(preparation, "_binary", lambda name: "/fixture/bin/" + name)
    monkeypatch.setattr(preparation, "_run", run)
    return commands


def _prepare(path: Path, settings: Settings) -> preparation.PreparedVideo:
    return preparation.prepare_uploaded_video(path, f"/data/videos/{path.name}", settings)


def test_preparation_defaults_off_and_never_runs_tools(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    settings = Settings(_env_file=None, data_dir=tmp_path / "data")
    assert settings.video_preparation_enabled is False
    monkeypatch.setattr(preparation, "_binary", lambda _name: pytest.fail("tool must not run"))
    with pytest.raises(preparation.VideoPreparationError, match="disabled"):
        _prepare(_source(settings), settings)


def test_incompatible_source_is_preserved_and_atomically_published_as_mp4(
    tmp_path: Path, fake_tools: list[list[str]]
) -> None:
    settings = _settings(tmp_path)
    source = _source(settings)
    original = source.read_bytes()
    result = _prepare(source, settings)
    assert source.read_bytes() == original
    assert result.original_sha256 == hashlib.sha256(original).hexdigest()
    assert result.status == "ready_normalized"
    assert result.path != source and result.path.suffix == ".mp4"
    assert result.url == f"/data/videos/{result.path.name}"
    assert result.path.stat().st_nlink == 1
    assert result.path.stat().st_mode & 0o777 == 0o600
    assert result.info.has_audio is False
    assert list((settings.data_dir / ".video-preparation").iterdir()) == [
        settings.data_dir / ".video-preparation" / "prepare.lock"
    ]
    command = next(arguments for arguments in fake_tools if "-c:v" in arguments)
    assert command[command.index("-protocol_whitelist") + 1] == "file"
    assert "hls" not in command[command.index("-format_whitelist") + 1]
    assert command[command.index("-c:v") + 1] == "libx264"
    assert command[command.index("-pix_fmt") + 1] == "yuv420p"
    assert command[command.index("-fps_mode") + 1] == "passthrough"
    assert "-r" not in command and "-hwaccel" not in command
    assert "-an" in command and "+faststart" in command


def test_compatible_mp4_is_reused_without_running_ffmpeg(
    tmp_path: Path, fake_tools: list[list[str]]
) -> None:
    settings = _settings(tmp_path)
    source = _source(settings, suffix=".mp4", payload=b"\x00\x00\x00\x18ftyp" + b"X" * 64)
    result = _prepare(source, settings)
    assert result.path == source
    assert result.status == "ready_original"
    assert all("-c:v" not in arguments for arguments in fake_tools)
    assert len(list(settings.videos_dir.iterdir())) == 1


@pytest.mark.parametrize(
    "payload",
    [
        b"",
        b"#EXTM3U\nhttps://secret.test/live",
        b"<xml/>",
        b"file '/etc/passwd'",
        b"not video",
    ],
)
def test_invalid_or_playlist_upload_never_invokes_decoder(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, payload: bytes
) -> None:
    settings = _settings(tmp_path)
    source = _source(settings, suffix=".mp4", payload=payload)
    monkeypatch.setattr(
        preparation, "_binary", lambda _name: pytest.fail("unsafe header reached a tool")
    )
    with pytest.raises(preparation.VideoPreparationError):
        _prepare(source, settings)
    assert source.read_bytes() == payload


@pytest.mark.parametrize("kind", ["symlink", "hardlink", "outside", "directory"])
def test_source_must_be_one_regular_owned_local_file(tmp_path: Path, kind: str) -> None:
    settings = _settings(tmp_path)
    source = _source(settings)
    if kind == "symlink":
        target = source.with_name("link.avi")
        target.symlink_to(source)
        source = target
    elif kind == "hardlink":
        os.link(source, source.with_name("linked.avi"))
    elif kind == "outside":
        source = tmp_path / "outside.avi"
        source.write_bytes(b"RIFF" + b"\x00" * 4 + b"AVI ")
    else:
        source = source.with_name("directory.avi")
        source.mkdir()
    with pytest.raises(preparation.VideoPreparationError, match="invalid_source"):
        _prepare(source, settings)


def test_input_size_is_limited_before_probing(tmp_path: Path) -> None:
    settings = _settings(tmp_path, upload_video_max_bytes=10)
    with pytest.raises(preparation.VideoPreparationError, match="input_limit"):
        _prepare(_source(settings), settings)


def test_missing_binary_reports_no_sensitive_argument(tmp_path: Path) -> None:
    settings = _settings(tmp_path, video_ffprobe_binary="missing-credential-secret-tool")
    with pytest.raises(preparation.VideoPreparationError) as caught:
        _prepare(_source(settings), settings)
    assert caught.value.code == "tool_unavailable"
    assert "secret" not in str(caught.value)


@pytest.mark.parametrize(
    ("values", "code"),
    [
        ({"duration": "NaN"}, "duration_unknown"),
        ({"duration": "inf"}, "duration_unknown"),
        ({"duration": "301"}, "duration_limit"),
        ({"width": 4096, "height": 2160}, "pixel_limit"),
        ({"width": True}, "invalid_video"),
        ({"height": 0}, "invalid_video"),
        ({"codec_name": "unsafe\nmetadata"}, "probe_failed"),
    ],
)
def test_probe_metadata_is_finite_bounded_and_explainable(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, values: dict[str, Any], code: str
) -> None:
    settings = _settings(tmp_path)
    payload = json.loads(_metadata())
    payload["streams"][0].update(values)
    if "duration" in values:
        payload["format"]["duration"] = values["duration"]
    monkeypatch.setattr(preparation, "_run", lambda *_args, **_kwargs: json.dumps(payload).encode())
    with pytest.raises(preparation.VideoPreparationError, match=code):
        preparation._probe(_source(settings), "/fixture/ffprobe", settings, float("inf"))


@pytest.mark.parametrize("payload", [b"not-json", b"[]", b'{"streams":[]}', b'{"streams":[{}]}'])
def test_probe_rejects_missing_or_malformed_fields(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, payload: bytes
) -> None:
    settings = _settings(tmp_path)
    monkeypatch.setattr(preparation, "_run", lambda *_args, **_kwargs: payload)
    with pytest.raises(preparation.VideoPreparationError):
        preparation._probe(_source(settings), "/fixture/ffprobe", settings, float("inf"))


def test_kernel_lock_rejects_overlap_and_recovers_without_deleting_inode(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    _source(settings)
    with preparation._preparation_lock(settings) as work:
        inode = (work / "prepare.lock").stat().st_ino
        with pytest.raises(preparation.VideoPreparationError, match="transcode_busy"):
            with preparation._preparation_lock(settings):
                pytest.fail("overlapping lock acquired")
    with preparation._preparation_lock(settings) as recovered:
        assert (recovered / "prepare.lock").stat().st_ino == inode


@pytest.mark.parametrize("kind", ["symlink", "hardlink"])
def test_shared_lock_rejects_unsafe_links(tmp_path: Path, kind: str) -> None:
    settings = _settings(tmp_path)
    _source(settings)
    work = settings.data_dir / ".video-preparation"
    work.mkdir()
    target = tmp_path / "outside.lock"
    target.write_bytes(b"fixture lock")
    if kind == "symlink":
        (work / "prepare.lock").symlink_to(target)
    else:
        os.link(target, work / "prepare.lock")
    with pytest.raises(preparation.VideoPreparationError, match="invalid_lock"):
        with preparation._preparation_lock(settings):
            pytest.fail("unsafe lock acquired")


def test_disk_budget_is_checked_before_transcode(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, fake_tools: list[list[str]]
) -> None:
    settings = _settings(tmp_path)
    monkeypatch.setattr(preparation.shutil, "disk_usage", lambda _path: SimpleNamespace(free=0))
    source = _source(settings)
    with pytest.raises(preparation.VideoPreparationError, match="disk_limit"):
        _prepare(source, settings)
    assert all("-c:v" not in arguments for arguments in fake_tools)
    assert len(list(settings.videos_dir.iterdir())) == 1


@pytest.mark.parametrize("failure", ["transcode_timeout", "transcode_failed", "output_limit"])
def test_failure_never_publishes_partial_or_removes_original(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, fake_tools: list[list[str]], failure: str
) -> None:
    settings = _settings(tmp_path)
    source = _source(settings)
    old = source.read_bytes()
    run = preparation._run

    def fail(arguments: list[str], **kwargs: Any) -> bytes:
        if "-c:v" in arguments:
            Path(arguments[-1]).write_bytes(b"partial output")
            raise preparation.VideoPreparationError(failure)
        return run(arguments, **kwargs)

    monkeypatch.setattr(preparation, "_run", fail)
    with pytest.raises(preparation.VideoPreparationError, match=failure):
        _prepare(source, settings)
    assert source.read_bytes() == old
    assert list(settings.videos_dir.iterdir()) == [source]
    assert len(list((settings.data_dir / ".video-preparation").iterdir())) == 1


@pytest.mark.parametrize("change", ["duration", "codec", "audio", "missing", "oversize", "source"])
def test_invalid_or_incomplete_output_cannot_be_published(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, fake_tools: list[list[str]], change: str
) -> None:
    settings = _settings(tmp_path)
    source = _source(settings)
    run = preparation._run

    def corrupt(arguments: list[str], **kwargs: Any) -> bytes:
        result = run(arguments, **kwargs)
        if "-c:v" in arguments:
            output = Path(arguments[-1])
            if change == "missing":
                output.unlink()
            elif change == "oversize":
                output.write_bytes(b"X" * 1024)
            elif change == "source":
                source.write_bytes(source.read_bytes() + b"changed")
        if arguments[-1].endswith(".partial") and "-select_streams" in arguments:
            selector = arguments[arguments.index("-select_streams") + 1]
            if change == "audio" and selector == "a:0":
                return b'{"streams":[{"codec_name":"aac"}]}'
            if selector == "v:0" and change in {"duration", "codec"}:
                return _metadata(
                    codec="h264" if change == "duration" else "mjpeg",
                    duration="0.1" if change == "duration" else "0.5",
                )
        return result

    monkeypatch.setattr(preparation, "_run", corrupt)
    with pytest.raises(preparation.VideoPreparationError):
        _prepare(source, settings)
    assert list(settings.videos_dir.iterdir()) == [source]


def test_optional_audio_uses_aac_only_when_explicitly_enabled(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, fake_tools: list[list[str]]
) -> None:
    settings = _settings(tmp_path, video_preparation_include_audio=True)
    run = preparation._run

    def audio(arguments: list[str], **kwargs: Any) -> bytes:
        if (
            "-select_streams" in arguments
            and arguments[arguments.index("-select_streams") + 1] == "a:0"
        ):
            codec = "aac" if arguments[-1].endswith(".partial") else "pcm_s16le"
            return json.dumps({"streams": [{"codec_name": codec}]}).encode()
        return run(arguments, **kwargs)

    monkeypatch.setattr(preparation, "_run", audio)
    result = _prepare(_source(settings), settings)
    command = next(arguments for arguments in fake_tools if "-c:v" in arguments)
    assert command[command.index("-c:a") + 1] == "aac"
    assert "-an" not in command
    assert result.info.has_audio


def test_subprocess_stdout_is_bounded_and_errors_do_not_echo_stderr(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    with pytest.raises(preparation.VideoPreparationError, match="probe_output_limit"):
        preparation._run(
            [sys.executable, "-c", "print('x' * 70000)"],
            timeout=2.0,
            failure_code="probe_failed",
            settings=settings,
        )
    with pytest.raises(preparation.VideoPreparationError) as error:
        preparation._run(
            [
                sys.executable,
                "-c",
                "import sys; print('secret-token', file=sys.stderr); sys.exit(1)",
            ],
            timeout=2.0,
            failure_code="probe_failed",
            settings=settings,
        )
    assert "secret" not in str(error.value)


def test_subprocess_timeout_kills_and_reaps_the_child(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    with pytest.raises(preparation.VideoPreparationError, match="probe_timeout"):
        preparation._run(
            [sys.executable, "-c", "import time; time.sleep(2)"],
            timeout=0.1,
            failure_code="probe_failed",
            settings=settings,
        )


def _database(tmp_path: Path) -> tuple[Any, Any]:
    from app.db.session import Base

    for name in ("persons", "events", "media", "vectors", "chat", "reid"):
        importlib.import_module(f"app.models.{name}")
    engine = create_engine(
        f"sqlite:///{tmp_path / 'synthetic.sqlite'}", connect_args={"check_same_thread": False}
    )
    Base.metadata.create_all(engine)
    return engine, sessionmaker(bind=engine, expire_on_commit=False)


def test_enabled_upload_extracts_from_persisted_playback_not_original(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, fake_tools: list[list[str]]
) -> None:
    from app.models.media import VideoAsset
    from app.schemas.media import VideoProcessResponse
    from app.services.video_processing import VideoProcessingService

    settings = _settings(tmp_path)
    engine, sessions = _database(tmp_path)
    original = b"RIFF" + b"\x00" * 4 + b"AVI " + b"X" * 64
    try:
        with sessions() as db:
            service = VideoProcessingService(db, settings)
            seen: dict[str, Any] = {}

            def process(**kwargs: Any) -> VideoProcessResponse:
                seen.update(kwargs)
                return VideoProcessResponse(
                    video_url=kwargs["video_url"],
                    frame_interval_seconds=0.1,
                    frames_read=0,
                    frames_sampled=0,
                    images_created=0,
                    crops_created=0,
                    counting_events_created=0,
                    image_ids=[],
                    crop_ids=[],
                )

            monkeypatch.setattr(service, "process_video_path", process)
            result = service.process_upload(
                UploadFile(file=BytesIO(original), filename="source.avi")
            )
            asset = db.get(VideoAsset, result.video_id)
            assert asset and asset.processing_status == "complete"
            assert asset.preparation_status == "ready_normalized"
            assert asset.playback_video_url == result.video_url == seen["video_url"]
            assert seen["video_path"].name == Path(asset.playback_video_url).name
            assert result.original_video_url == asset.original_video_url
            assert service._resolve_data_url(asset.original_video_url).read_bytes() == original
            assert result.has_audio is False
    finally:
        engine.dispose()


def test_failed_preparation_persists_original_ownership_and_safe_reason(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from app.models.media import VideoAsset
    from app.services import video_processing
    from app.services.video_processing import VideoProcessingService

    settings = _settings(tmp_path)
    engine, sessions = _database(tmp_path)
    original = b"RIFF" + b"\x00" * 4 + b"AVI " + b"X" * 64

    def fail(*_args: Any) -> None:
        raise preparation.VideoPreparationError("transcode_timeout", 503)

    monkeypatch.setattr(video_processing, "prepare_uploaded_video", fail)
    try:
        with sessions() as db:
            service = VideoProcessingService(db, settings)
            with pytest.raises(preparation.VideoPreparationError) as error:
                service.process_upload(UploadFile(file=BytesIO(original), filename="source.avi"))
            asset = db.get(VideoAsset, error.value.video_id)
            assert asset and asset.preparation_status == "failed"
            assert asset.reason == "transcode_timeout"
            assert asset.playback_video_url is None
            assert service._resolve_data_url(asset.original_video_url).read_bytes() == original
    finally:
        engine.dispose()


def test_clips_query_is_real_paginated_and_unknown_video_returns_404(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from app.api.media import router
    from app.api.media_files import MediaStaticFiles
    from app.config.settings import get_settings
    from app.db.session import get_db
    from app.models.media import Image, PersonCrop, VideoAsset

    settings = _settings(tmp_path)
    source = _source(settings, suffix=".mp4", payload=b"\x00\x00\x00\x18ftyp" + b"X" * 64)
    engine, sessions = _database(tmp_path)
    url = f"/data/videos/{source.name}"
    try:
        with sessions() as db:
            asset = VideoAsset(
                original_video_url=url,
                playback_video_url=url,
                preparation_status="ready_original",
                processing_status="complete",
                duration_seconds=2.0,
                has_audio=False,
            )
            db.add(asset)
            images = [
                Image(
                    image_url=f"/data/frames/{index}.jpg",
                    source_type="video_frame",
                    source_video_url=url,
                    video_offset_seconds=index * 0.1,
                    captured_at=datetime(2026, 10, 7, tzinfo=UTC),
                )
                for index in range(3)
            ]
            db.add_all(images)
            db.flush()
            crop = PersonCrop(image_id=images[1].id, crop_url="/data/crops/example.jpg", bbox={})
            db.add(crop)
            db.commit()
            asset_id, image_id, crop_id = asset.id, images[1].id, crop.id

        def isolated_db() -> Any:
            with sessions() as db:
                yield db

        api = FastAPI()
        api.dependency_overrides[get_db] = isolated_db
        api.dependency_overrides[get_settings] = lambda: settings
        api.include_router(router, prefix="/api")
        api.mount("/data", MediaStaticFiles(directory=settings.data_dir))
        monkeypatch.setattr(
            preparation,
            "prepare_uploaded_video",
            lambda *_args: pytest.fail("GET must not prepare"),
        )
        with TestClient(api) as client:
            assert client.get(f"/api/videos/{uuid.uuid4()}/clips").status_code == 404
            clips = client.get(f"/api/videos/{asset_id}/clips?limit=1&offset=1")
            assert clips.status_code == 200
            payload = clips.json()
            assert payload["total"] == 3 and len(payload["items"]) == 1
            assert payload["items"][0]["image_id"] == str(image_id)
            assert payload["items"][0]["crop_ids"] == [str(crop_id)]
            assert payload["items"][0]["offset_seconds"] == 0.1
            for route in (f"images/{image_id}", f"person-crops/{crop_id}"):
                replay = client.get(f"/api/{route}/playback").json()
                assert replay["available"] and replay["offset_seconds"] == 0.1
                assert replay["video_id"] == str(asset_id)
                assert replay["compatibility_status"] == "ready_original"
                assert replay["original_video_url"] == url
            assert client.get(url, headers={"Range": "bytes=0-7"}).status_code == 206
    finally:
        engine.dispose()


def test_real_generated_avi_can_prepare_h264_when_cli_is_available(tmp_path: Path) -> None:
    """Optional local-only encoder integration; never downloads tools or media."""
    if shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None:
        pytest.skip("FFmpeg/FFprobe CLI not installed locally")
    cv2, np = pytest.importorskip("cv2"), pytest.importorskip("numpy")
    settings = _settings(tmp_path, video_preparation_max_output_bytes=1024 * 1024)
    settings.videos_dir.mkdir(parents=True)
    source = settings.videos_dir / "synthetic.avi"
    writer = cv2.VideoWriter(str(source), cv2.VideoWriter_fourcc(*"MJPG"), 10.0, (64, 48))
    if not writer.isOpened():
        pytest.skip("Local MJPG writer unavailable")
    try:
        for index in range(5):
            writer.write(np.full((48, 64, 3), index * 30, dtype=np.uint8))
    finally:
        writer.release()
    original = source.read_bytes()
    result = _prepare(source, settings)
    assert result.status == "ready_normalized"
    assert result.info.codec == "h264" and result.info.pixel_format == "yuv420p"
    assert result.info.duration_seconds == pytest.approx(0.5, abs=0.01)
    assert source.read_bytes() == original
    capture = cv2.VideoCapture(str(result.path))
    try:
        offsets = []
        while capture.read()[0]:
            offsets.append(capture.get(cv2.CAP_PROP_POS_MSEC) / 1000.0)
        assert offsets == pytest.approx([0.0, 0.1, 0.2, 0.3, 0.4], abs=0.01)
    finally:
        capture.release()


def test_init_db_creates_video_asset_table_and_preserves_legacy_rows(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from sqlalchemy import inspect, select, text

    from app.db import session
    from app.models.media import VideoAsset

    engine = create_engine(f"sqlite:///{tmp_path / 'legacy.sqlite'}")
    monkeypatch.setattr(session, "engine", engine)
    try:
        with engine.begin() as connection:
            connection.execute(
                text("CREATE TABLE images (id VARCHAR PRIMARY KEY, captured_at DATETIME)")
            )
            connection.execute(text("INSERT INTO images (id) VALUES ('historical-frame')"))
        session.init_db()
        columns = {column["name"] for column in inspect(engine).get_columns("images")}
        assert {"processed_at", "source_video_url", "video_offset_seconds"} <= columns
        assert "video_assets" in inspect(engine).get_table_names()
        sessions = sessionmaker(bind=engine)
        with sessions() as db:
            asset = VideoAsset(
                original_video_url="/data/videos/synthetic.avi",
                preparation_status="failed",
                reason="transcode_timeout",
            )
            db.add(asset)
            db.commit()
            asset_id = asset.id
        session.init_db()
        with sessions() as db:
            assert db.get(VideoAsset, asset_id).reason == "transcode_timeout"
            assert db.scalar(select(VideoAsset.id)) == asset_id
            assert db.execute(text("SELECT * FROM images")).one() == (
                "historical-frame",
                None,
                None,
                None,
                None,
            )
    finally:
        engine.dispose()


@pytest.mark.parametrize("partial", [False, True])
def test_prepared_processing_failure_preserves_both_files_and_committed_progress(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    fake_tools: list[list[str]],
    partial: bool,
) -> None:
    from sqlalchemy import select

    from app.models.media import Image, VideoAsset
    from app.services.vector_index_queue import VectorQueueFullError
    from app.services.video_processing import (
        VideoProcessingBackpressureError,
        VideoProcessingService,
    )

    settings = _settings(tmp_path)
    engine, sessions = _database(tmp_path)
    original = b"RIFF" + b"\x00" * 4 + b"AVI " + b"X" * 64
    try:
        with sessions() as db:
            service = VideoProcessingService(db, settings)
            committed_id = uuid.uuid4()

            def process(**kwargs: Any) -> None:
                if partial:
                    db.add(
                        Image(
                            id=committed_id,
                            image_url="/data/frames/committed.jpg",
                            source_type="video_frame",
                            source_video_url=kwargs["video_url"],
                            video_offset_seconds=0.1,
                        )
                    )
                    db.commit()
                    raise VideoProcessingBackpressureError(
                        VectorQueueFullError("queue full"),
                        frames_read=2,
                        frames_sampled=2,
                        frames_processed=1,
                        image_ids=[committed_id],
                        crop_ids=[],
                        counting_events_created=0,
                    )
                raise RuntimeError("/secret/private/media token=private")

            monkeypatch.setattr(service, "process_video_path", process)
            expected = (
                VideoProcessingBackpressureError if partial else preparation.VideoPreparationError
            )
            with pytest.raises(expected) as error:
                service.process_upload(UploadFile(file=BytesIO(original), filename="source.avi"))
            asset = db.scalar(select(VideoAsset))
            assert asset and error.value.video_id == asset.id
            assert asset.preparation_status == "ready_normalized"
            assert asset.processing_status == ("partial" if partial else "failed")
            assert asset.reason == ("vector_index_queue_full" if partial else "processing_failed")
            assert service._resolve_data_url(asset.original_video_url).read_bytes() == original
            assert service._resolve_data_url(asset.playback_video_url).is_file()
            if partial:
                assert db.get(Image, committed_id).source_video_url == asset.playback_video_url
                assert error.value.api_detail()["video_id"] == str(asset.id)
                assert error.value.api_detail()["images_committed"] == 1
            else:
                assert "private" not in str(error.value) and error.value.status_code == 422
    finally:
        engine.dispose()


def test_failed_upload_api_returns_safe_video_id_and_queryable_failure_state(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from app.api.media import router
    from app.config.settings import get_settings
    from app.db.session import get_db
    from app.models.media import VideoAsset
    from app.services import video_processing

    settings = _settings(tmp_path)
    engine, sessions = _database(tmp_path)

    def fail(*_args: Any) -> None:
        raise preparation.VideoPreparationError("transcode_busy", 503)

    def isolated_db() -> Any:
        with sessions() as db:
            yield db

    monkeypatch.setattr(video_processing, "prepare_uploaded_video", fail)
    api = FastAPI()
    api.dependency_overrides[get_db] = isolated_db
    api.dependency_overrides[get_settings] = lambda: settings
    api.include_router(router, prefix="/api")
    original = b"RIFF" + b"\x00" * 4 + b"AVI " + b"X" * 64
    try:
        with TestClient(api) as client:
            response = client.post(
                "/api/videos/upload", files={"file": ("source.avi", original, "video/x-msvideo")}
            )
            assert response.status_code == 503
            detail = response.json()["detail"]
            assert detail["code"] == "transcode_busy"
            video_id = uuid.UUID(detail["video_id"])
            payload = client.get(f"/api/videos/{video_id}/clips").json()
            assert payload["compatibility_status"] == "failed"
            assert payload["reason"] == "transcode_busy" and payload["total"] == 0
            assert payload["items"] == [] and payload["has_audio"] is None
            assert client.get(f"/api/videos/{video_id}/clips?limit=201").status_code == 422
        with sessions() as db:
            asset = db.get(VideoAsset, video_id)
            assert (
                settings.videos_dir / Path(asset.original_video_url).name
            ).read_bytes() == original
    finally:
        engine.dispose()


@pytest.mark.parametrize("duration", [None, 0.0, -1.0, float("inf"), float("nan"), True, 0.1])
def test_prepared_playback_requires_offset_inside_verified_duration(
    tmp_path: Path, duration: float | None
) -> None:
    from app.models.media import Image, VideoAsset
    from app.services.video_playback import video_playback_for_image

    settings = _settings(tmp_path)
    source = _source(settings, suffix=".mp4")
    url = f"/data/videos/{source.name}"
    image = Image(
        image_url="/data/frames/example.jpg",
        source_type="video_frame",
        source_video_url=url,
        video_offset_seconds=0.1,
    )
    asset = VideoAsset(
        id=uuid.uuid4(),
        original_video_url=url,
        playback_video_url=url,
        preparation_status="ready_original",
        duration_seconds=duration,
    )
    result = video_playback_for_image(image, settings, asset)
    assert not result.available and result.reason == "offset_out_of_range"
    assert result.video_url is None and result.offset_seconds is None


@pytest.mark.parametrize(
    ("asset_url", "status", "reason"),
    [
        ("/data/videos/unrelated.mp4", "ready_normalized", "invalid_source"),
        (None, "preparing", "invalid_source"),
        ("match", "failed", "video_not_ready"),
        ("match", "preparing", "video_not_ready"),
    ],
)
def test_unverified_asset_never_becomes_playback(
    tmp_path: Path, asset_url: str | None, status: str, reason: str
) -> None:
    from app.models.media import Image, VideoAsset
    from app.services.video_playback import video_playback_for_image

    settings = _settings(tmp_path)
    source = _source(settings, suffix=".mp4")
    url = f"/data/videos/{source.name}"
    image = Image(
        image_url="/data/frames/example.jpg",
        source_type="video_frame",
        source_video_url=url,
        video_offset_seconds=0.0,
    )
    asset = VideoAsset(
        id=uuid.uuid4(),
        original_video_url=url,
        playback_video_url=url if asset_url == "match" else asset_url,
        preparation_status=status,
        duration_seconds=1.0,
    )
    assert video_playback_for_image(image, settings, asset).reason == reason


@pytest.mark.parametrize(
    "module_name",
    ["scripts.cleanup_media_before", "scripts.cleanup_non_crossing_stream_frames"],
)
def test_cleanup_preserves_all_video_assets_even_failed_unindexed_and_unknown_videos(
    tmp_path: Path, module_name: str
) -> None:
    from app.models.media import VideoAsset
    from app.services.video_retention import video_asset_media_urls

    cleanup = importlib.import_module(module_name)
    settings = _settings(tmp_path)
    original, playback, unowned = [_source(settings) for _ in range(3)]
    settings.frames_dir.mkdir(parents=True, exist_ok=True)
    retired = settings.frames_dir / "retired.jpg"
    protected = settings.frames_dir / "owned.jpg"
    retired.write_bytes(b"retired frame")
    protected.write_bytes(b"non-video protected reference")
    engine, sessions = _database(tmp_path)
    try:
        with sessions() as db:
            db.add_all(
                [
                    VideoAsset(
                        original_video_url=f"/data/videos/{original.name}",
                        playback_video_url=f"/data/videos/{playback.name}",
                        preparation_status="failed",
                    ),
                    VideoAsset(original_video_url="/data/frames/owned.jpg"),
                ]
            )
            db.commit()
            protected_urls = video_asset_media_urls(db)
            assert f"/data/videos/{original.name}" in protected_urls
            assert f"/data/videos/{playback.name}" in protected_urls
            removed = cleanup.remove_files(
                settings.data_dir,
                [
                    (f"/data/videos/{original.name}", f"/data/videos/{playback.name}"),
                    (f"/data/videos/{unowned.name}", "/data/frames/owned.jpg"),
                    ("/data/frames/retired.jpg", None),
                ],
                protected_urls,
            )
        assert removed == 1 and not retired.exists()
        assert (
            original.is_file() and playback.is_file() and unowned.is_file() and protected.is_file()
        )
    finally:
        engine.dispose()


def test_cleanup_legacy_schema_and_unsafe_file_targets_remain_safe(tmp_path: Path) -> None:
    from app.services.video_retention import remove_retired_image_files, video_asset_media_urls

    settings = _settings(tmp_path)
    settings.frames_dir.mkdir(parents=True)
    outside = tmp_path / "outside.jpg"
    outside.write_bytes(b"outside")
    (settings.frames_dir / "link.jpg").symlink_to(outside)
    os.link(outside, settings.frames_dir / "hardlink.jpg")
    (settings.frames_dir / "directory.jpg").mkdir()
    engine = create_engine(f"sqlite:///{tmp_path / 'legacy.sqlite'}")
    try:
        with sessionmaker(bind=engine)() as db:
            assert video_asset_media_urls(db) == frozenset()
        assert (
            remove_retired_image_files(
                settings.data_dir,
                [
                    ("/data/../outside.jpg", "/data/frames/../../outside.jpg"),
                    ("/data/frames/link.jpg", "/data/frames/hardlink.jpg"),
                    ("/data/frames/directory.jpg", "/data/frames/missing.jpg"),
                ],
            )
            == 0
        )
        assert outside.read_bytes() == b"outside"
        assert (settings.frames_dir / "link.jpg").is_symlink()
    finally:
        engine.dispose()
